#!/usr/bin/bash

../../mysql/bin/mysql.exe jazztownsville < ../../htdocs/jazztownsville/export/jazztownsville.sql -u root

if [ $? != 0 ]; then
  echo "Could not pull, Xampp is not running!"
  git reset -q --hard HEAD^
  exit 1
fi

exit 0