#!/usr/bin/bash

rm export/* -f

../../php/php.exe wp-cli.phar export --dir=export
../../mysql/bin/mysqldump.exe jazztownsville > ../../htdocs/jazztownsville/export/jazztownsville.sql -u root

if [ $? != 0 ]; then
  echo "Could not commit, Xampp is not running!"
  exit 1
fi

git add export

exit 0