#!/usr/bin/bash

cd export

rm ./* -f

../../php/php.exe wp-cli.phar export
../../php/php.exe wp-cli.phar db export jazztownsville.sql

if [ $? != 0 ]; then
  echo "Could not commit, Xampp is not running!"
  exit 1
fi

git add export

exit 0