# This is a basic workflow to help you get started with Actions

name: Create Distributable Theme

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls -h
          npm install
          npm run dist
          npm run dist-build
          ls -h dist
          git clone -b dist https://github.com/cp3402-students/cp3402-2022-1-site-team01.git ../dist
          rm -r -f ../dist/*
          mv dist/* ../dist
          cd ../dist
          ls -h
          rm LICENSE
          rm README.md
          rm deployment.md
          rm site.md
          rm theme.md
