# This is a basic workflow to help you get started with Actions

name: Create Distributable Theme

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls -h
          npm install
          npm run dist
          npm run dist-build
          mv dist ../dist
          git fetch
          git checkout dist
          rm -r -f ./*
          mv ../dist/* .
          rm LICENSE
          rm README.md
          rm deployment.md
          rm site.md
          rm theme.md
          cat <<EOT > style.css
          /*
            Theme Name:   Jazz Townsville
            Theme URI:    https://understrap.com
            Description:
            Author:       Gauvan and the Boys
            Author URI:   https://github.com/understrap/understrap-child/graphs/contributors
            Template:     understrap
            Version:      1.1.0
            License: GNU General Public License v2 or later
            License URI: http://www.gnu.org/licenses/gpl-2.0.html
            Text Domain:  understrap-child
            Tags: one-column, custom-menu, featured-images, theme-options, translation-ready
            GitHub Theme URI: understrap/understrap-child
          */
          EOT
          ls -h
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git status
          git diff --quiet && git diff --staged --quiet || git commit -am 'Create distributable theme'
          git push
